query GetProjectById($id: uuid!) {
  projects_by_pk(id: $id) {
    id
    image
    title
    created_at
    updated_at
    spaces(order_by: {created_at: asc}) {
      id
      name
      edges
      components
    }
    styles(order_by: {created_at: asc}) {
      id
      name
      style
    }
    tokens(order_by: {created_at: asc}) {
      id
      name
      tokens
    }
  }
}

query GetProjectsByUser($id: uuid!) {
  projects(where: {owner_user_id: {_eq: $id}}, order_by: {updated_at: desc}) {
    id
    image
    title
    created_at
    updated_at
  }
}
