mutation InsertProject($title: String!) {
  insert_projects_one(object: {
    title: $title,
    spaces: {
      data: {
        name: "Space 1",
        edges: [],
        components: []
      }
    }
    tokens: {
      data: {
        name: "Tokens 1",
        tokens: ""
      }
    }
  }) {
    id
    image
    title
    created_at
    updated_at
    spaces {
      id
      name
      edges
      components
    }
    styles {
      id
      name
      style
    }
    tokens {
      id
      name
      tokens
    }
  }
}

mutation SaveStyle($id: uuid!, $style: String!, $name: String!) {
  update_styles_by_pk(pk_columns: {id: $id}, _set: {style: $style, name: $name}) {
    updated_at
  }
}

mutation SaveTokens($id: uuid!, $tokens: String!, $name: String!) {
  update_tokens_by_pk(pk_columns: {id: $id}, _set: {tokens: $tokens, name: $name}) {
    updated_at
  }
}

mutation SaveProject($id: uuid!, $title: String!) {
  update_projects_by_pk(pk_columns: {id: $id}, _set: {title: $title}) {
    updated_at
  }
}

mutation SaveSpace($id: uuid!, $name: String!, $edges: jsonb!, $components: jsonb!) {
  update_spaces_by_pk(pk_columns: {id: $id}, _set: {name: $name, edges: $edges, components: $components}) {
    updated_at
  }
}

mutation CreateStyle($name: String!, $projectId: uuid!) {
  insert_styles_one(object: {name: $name, project_id: $projectId, style: ""}) {
    id
  }
}

mutation CreateTokens($name: String!, $projectId: uuid!) {
  insert_tokens_one(object: {name: $name, project_id: $projectId, tokens: ""}) {
    id
  }
}

mutation CreateSpace($name: String!, $projectId: uuid!) {
  insert_spaces_one(object: {name: $name, project_id: $projectId}) {
    id
  }
}
